### PR TITLE
Fix TOC not reflecting changes made by config()->set and add test case for multiple settings

### LINKED ISSUE #77: TOC does not reflect changes made by config()->set
### Bug Description

Following the example provided in [the documentation](https://benjaminhoegh.github.io/ParsedownExtended/Configuration/Table%20of%20Contents#customize-toc) does not yield the expected result. Instead, nothing happens.

Here is the output of '`toc'` from var_export on `$parsedown->config()`:
```
'toc' => 
    array (
      'enabled' => 
      array (
        'headings' => 
        array (
          0 => 'h1',
          1 => 'h2',
          2 => 'h3',
        ),
        'tag' => '[toc]',
        'id' => 'table-of-contents',
      ),
      'levels' => 
      array (
        0 => 'h1',
        1 => 'h2',
        2 => 'h3',
        3 => 'h4',
        4 => 'h5',
        5 => 'h6',
      ),
      'tag' => '[TOC]',
      'id' => 'toc',
    ),
```

Here is the minimal example which produces this result:
```
<?php

require_once("_parsedown.php");
require_once("_parsedownExtra.php");
require_once("_parsedownExtended.php");

$parsedown = new \BenjaminHoegh\ParsedownExtended\ParsedownExtended();

// straight from the documentation
$parsedown->config()->set('toc', [
    'headings' => ['h1', 'h2', 'h3'], // Headings to include
    'tag' => '[this-is-the-toc]', // Custom ToC tag
    'id' => 'table-of-contents', // Custom ToC ID
]);

$text = $parsedown->text("
# heading 1
text

[TOC]

[this-is-the-toc]

## subheading 1
text2

### subheading 3
text3

#### subheading 4
text4 - this should not be included in the toc

# heading 2
text5

## subheading 2
text6

# heading 3
text7
");

echo $text;
?>
```

The table of contents will be output with the default `toc` id and all levels included, although only headings up to h3 should be included, and `[this-is-the-toc]` will be ignored. Either the documentation is wrong, or there is a bug, but my junior eyes couldn't find anything wrong with the config->set method at a quick glance.

Everything else works as intended and this project is delightful 🙏🏼 

### PHP Version

8.2

### Parsedown Version

1.8.0

### Parsedown Extra Version

0.8.0 - commit acebd17

### Code of Conduct

- [X] I agree to follow the project's Code of Conduct.

### PR DESCRIPTION
**Pull request by BenjaminHoegh**
The table of contents (TOC) was not correctly reflecting changes made through the configuration settings. This update ensures that the TOC respects the custom tag and levels specified in the configuration. Additionally, a new test case has been added to verify the functionality of the TOC with multiple settings applied simultaneously. Fixes #77

### CODE REVIEW

File: src/ParsedownExtended.php [hunk 1]
```diff
@@ -3414,7 +3414,7 @@ private function translateDeprecatedKeyPath(string $keyPath): string
              * @return mixed The value of the configuration setting.
              * @throws \InvalidArgumentException If the key path is invalid.
              */
-            public function get(string $keyPath)
+            public function get(string $keyPath, bool $raw = false)
```
Comment (kennyrkun) [inline src/ParsedownExtended.php:3417]: parameter `$raw` is not documented
